### ISSUE TITLE
Not detecting all faces in a photo.

### ISSUE THREAD

**Issue by rockneurotiko** [skgsergio/dogefy-tg-bot#1]
In [this](http://68.media.tumblr.com/e0f260ee0dc792669926419db984685d/tumblr_ofuz5ljYhv1uhsfpso1_500.jpg) photo dogefy only detects one face, but I see three.

**Comment by skgsergio** [comment]
Sorry @rockneurotiko, fix your own face recognition, the bot is working properly.

**Comment by rockneurotiko** [comment]
I like my face recognition xD
